# Generated by Django 3.0.7 on 2020-07-01 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_profile_birthday'),
    ]

    operations = [
        migrations.AddField(
            model_name='brocode',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
