# Generated by Django 3.0.7 on 2020-07-02 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20200702_0117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brocode',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Profile'),
        ),
    ]
